name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the repository 
      uses: actions/checkout@v2.4.0
    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow
    - name: Cache Tools
      uses: actions/cache@v2.1.7
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
    - name: Publishing documentaiton
      uses: cake-build/cake-action@v1.4.0
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        verbosity: Diagnostic
        cake-version: 0.38.5
        cake-bootstrap: true
